# Generated by Django 4.2.1 on 2023-05-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0003_remove_tutor_nome_alter_animal_especie_and_more'),
    ]

    operations = [
    ]
