# Generated by Django 4.2.1 on 2023-05-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0006_alter_animal_ani_anilha_alter_animal_ani_dnasc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Animal', to='registro_de_animais.animal', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['pk'],
            },
        ),
    ]
