# Generated by Django 4.2.1 on 2023-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0009_alter_animal_ani_foto_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ani_foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
