# Generated by Django 4.2.1 on 2023-05-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro_de_animais', '0011_alter_animal_ani_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='ani_anilha',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_castr',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_cor',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_dnasc',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_espec',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_foto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_idade',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_nmchip',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_obs',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_porte',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_raça',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_rga',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_sexo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_vacinado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_vermifugado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
