# Generated by Django 4.2.1 on 2023-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0012_remove_animal_ani_anilha_remove_animal_ani_castr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ani_anilha',
            field=models.CharField(blank=True, default='não informado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_castr',
            field=models.CharField(default='Não sei', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_cor',
            field=models.CharField(default='não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_dnasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_espec',
            field=models.CharField(default='não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pet_profile_pics'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_nmchip',
            field=models.CharField(blank=True, default='não informado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_obs',
            field=models.CharField(blank=True, default='não informado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_porte',
            field=models.CharField(default='não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_raça',
            field=models.CharField(default='não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_rga',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_sexo',
            field=models.CharField(default='não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_vacinado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ani_vermifugado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateField(default='2023-05-21'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ani_nome',
            field=models.CharField(default='não informado', max_length=50),
        ),
    ]
