# Generated by Django 4.2.1 on 2023-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0013_animal_ani_anilha_animal_ani_castr_animal_ani_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
