# Generated by Django 4.2.1 on 2023-05-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0015_alter_animal_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacina',
            name='animal_id',
        ),
        migrations.AddField(
            model_name='vacina',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='registro_de_animais.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ani_obs',
            field=models.CharField(blank=True, default='não informado', max_length=1000, null=True),
        ),
    ]
