# Generated by Django 4.2.1 on 2023-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_animais', '0016_remove_vacina_animal_id_vacina_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='vac_anexo',
            field=models.FileField(blank=True, null=True, upload_to='vacinas'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='vac_tipo',
            field=models.CharField(default=None, blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vac_data_admin',
            field=models.DateField(max_length=11),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vac_fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vac_nome',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='vac_num_dose',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
